name: GioSite
favicon: null
layout_spectrum: 0.8639901170972735
typography_spectrum: 0.60174505203031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#808080'
    - '#fdfdfd'
    - '#c2c2c2'
    - '#ffbf77'
    - '#252233'
  brandStrength: 0.6875
  lightness: 0.4923306256532669
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
