name: Natsu 夏
favicon: null
layout_spectrum: 0.8639901170972735
typography_spectrum: 0.60174505203031
title: Summer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#ce373e'
    - '#e6b08e'
    - '#73616d'
    - '#000100'
  brandStrength: 0.5
  lightness: 0.4923306256532669
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
